apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: karpenter
  source:
    repoURL: https://github.com/amazondevops/devops-all-tools.git
    targetRevision: HEAD
    path: eks-gitops/helm/charts/karpenter-resources
    helm:
      valueFiles:
      - ../../value-store/karpenter/nodePools.yaml
      - ../../value-store/karpenter/ec2NodeClass.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: false 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 


