apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-internal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: istio
  source:
    repoURL: https://github.com/amazondevops/devops-all-tools.git
    targetRevision: HEAD
    path: eks-gitops/helm/charts/istio-1.26/gateway
    helm:
      valueFiles:
      - ../../../value-store/istio-gateway/istio-internal-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: false 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 

