apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-ingress-nprod-internal
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  sources:
    # 1) Internal ALB Ingress (namespace: istio-system in the manifest)
    - repoURL: 'https://github.com/amazondevops/devops-all-tools.git'
      targetRevision: HEAD
      path: eks-gitops/helm/value-store/istio-ingress-alb
      directory:
        include: istio-internal-ingress-alb.yaml
    # 2) Internal Istio Gateway (namespace: default in the manifest)
    - repoURL: 'https://github.com/amazondevops/devops-all-tools.git'
      targetRevision: HEAD
      path: eks-gitops/helm/value-store/istio-gw
      directory:
        include: istio-internal-gateways.yaml
  project: istio
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
