apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: {{ .Values.service.ports.client.port }}
      protocol: TCP
      targetPort: {{ .Values.service.ports.client.targetPort }}
  selector:
    app: kafka-app
