---
fullnameOverride: prometheus-node-exporter

kubeRBACProxy:
  enabled: true
  tls:
    enabled: true
    tlsClientAuth: true

tlsSecret:
  enabled: true
  caItem: client-ca.crt
  secretName: '{{ include "prometheus-node-exporter.fullname" . }}-tls'
  volumeName: '{{ include "prometheus-node-exporter.fullname" . }}-tls'

extraManifests:
  - |
    apiVersion: v1
    data:
      client-ca.crt: ""
      tls.crt: ""
      tls.key: ""
    kind: Secret
    metadata:
      name: '{{ include "prometheus-node-exporter.fullname" . }}-tls'
