apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defectdojo
  namespace: argocd
spec:
  project: defectdojo
  source:
    repoURL: git@bitbucket.org:junglee_games/dmnd-pkrb-gitops-nprod.git
    targetRevision: HEAD
    path: helm/charts/defectdojo
    helm:
      valueFiles:
      - ../../value-store/defectdojo/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: defectdojo

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: false 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 

