{{- range .Values.awsNodeTemplates  }}
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: {{ .name }}
spec:
  {{- if .metadataOptions }}
  metadataOptions:
{{ .metadataOptions | toYaml | indent 4 }}
  {{- end }}
  tags: 
{{ .tags | toYaml | indent 4 }}
  subnetSelector:
    aws-ids: {{ .subnetIDs }}
  securityGroupSelector:
    aws-ids: {{ .securityGroupIDs }}
  instanceProfile: {{ .instanceProfile }}
  amiSelector:
    aws::ids: {{ .amiIDs }}
  blockDeviceMappings:
{{ toYaml .blockDeviceMappings | indent 4 }}   
---
{{- end }}

