{{- range .Values.nodePools }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}
spec:
  template:
    {{- if or .labels .doNotDisruptAnnotation }}
    metadata:
      {{- if .doNotDisruptAnnotation }}
      annotations:
        karpenter.sh/do-not-disrupt: "true"
      {{- end }}
      {{- if .labels }}
      labels:
{{ toYaml .labels | indent 8 }}
      {{- end }}
    {{- end }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .nodeClassRef }}
      {{- if .taints }}
      taints:
{{ toYaml .taints | indent 8 }}
      {{- end }}
      requirements:
{{ toYaml .requirements | indent 8 }}
      {{- if .expireAfter }}
      expireAfter: {{ .expireAfter }}
      {{- end }}
      {{- if .kubelet }}
      kubelet:
{{ toYaml .kubelet | indent 8 }}
      {{- end }}
  {{- if .disruption }}
  disruption:
{{ toYaml .disruption | indent 4 }}
  {{- end }}
  {{- if or .cpuLimits .memoryLimits }}
  limits:
    {{- if .cpuLimits }}
    cpu: {{ .cpuLimits }}
    {{- end }}
    {{- if .memoryLimits }}
    memory: {{ .memoryLimits }}
    {{- end }}
  {{- end }}
---
{{- end }}
