apiVersion: v1
kind: Service
metadata:
  name: zk-1
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: zk-1.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: zk-2
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: zk-2.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: zk-3
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: zk-3.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: kafka-1.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: kafka-2.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: kafka-3.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: pg-main-master
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: pg-main-master.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: pg-main-slave
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: pg-main-slave.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: pg-ticket-master
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: pg-ticket-master.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: pg-ticket-slave
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: pg-ticket-slave.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-main-pri
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: mongo-main-pri.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-main-sec
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: mongo-main-sec.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-aux-pri
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: mongo-aux-pri.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-aux-sec
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: mongo-aux-sec.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-p7
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: redis-p7.{{ .Values.spec.destination.hostedzone }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-p8
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  type: ExternalName
  externalName: redis-p8.{{ .Values.spec.destination.hostedzone }}