
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: poc-qa-1
  namespace: argocd
spec:
  description: poc-qa-1
  sourceRepos:
  - 'https://github.com/amazondevops/devops-all-tools.git'
  destinations:
  - namespace: poc-qa-1
    server: https://kubernetes.default.svc
  # the incubator app generates child Application CRs in the argocd namespace
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true