nodePools:
- name: pkrb-dev
  taints:
    - key: scheduler
      value: karpenter
      effect: NoSchedule
  labels:
    provisioner: karpenter-pkrb-dev
  nodeClassRef:
    name: pkrb-dev
    group: karpenter.k8s.aws
    kind: EC2NodeClass
  requirements:
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["c6a","m6a","c5a","m5a"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["4"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot","on-demand"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16", "32"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-south-1a","ap-south-1b","ap-south-1c"]
  cpuLimits: 80
  memoryLimits: 160G
  disruption:
    consolidateAfter: 1h
    consolidationPolicy: WhenEmptyOrUnderutilized


- name: rum-dev
  taints:
    - key: scheduler
      value: karpenter
      effect: NoSchedule
  labels:
    provisioner: karpenter-rum-dev
  nodeClassRef:
    name: rum-dev
    group: karpenter.k8s.aws
    kind: EC2NodeClass
  requirements:
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["c6a","m6a","c5a","m5a"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["4"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot","on-demand"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16", "32"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-south-1a","ap-south-1b","ap-south-1c"]
  cpuLimits: 30
  memoryLimits: 160G
  disruption:
    consolidateAfter: 1h
    consolidationPolicy: WhenEmptyOrUnderutilized


- name: aud-dev
  taints:
    - key: scheduler
      value: karpenter
      effect: NoSchedule
  labels:
    provisioner: karpenter-aud-dev
  nodeClassRef:
    name: aud-dev
    group: karpenter.k8s.aws
    kind: EC2NodeClass
  requirements:
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["c6a","m6a","c5a","m5a"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt
      values: ["4"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot","on-demand"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16", "32"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-south-1a","ap-south-1b","ap-south-1c"]
  cpuLimits: 30
  memoryLimits: 160G
  disruption:
    consolidateAfter: 1h
    consolidationPolicy: WhenEmptyOrUnderutilized
