apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver-provider-aws
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:junglee_games/dmnd-pkrb-gitops-nprod.git
    targetRevision: HEAD
    path: helm/charts/secrets-store-csi-driver-provider-aws
    helm:
      valueFiles:
      - ../../value-store/secrets-store-csi-driver-provider-aws/secrets-store-csi-driver-provider-aws.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: false 
      allowEmpty: false 
    syncOptions:     
    - Validate=false 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 


